version: "3.8"

services:
  postgres_db:
    container_name: postgres_db_container
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${MASTER_DB_USER}
      - POSTGRES_PASSWORD=${MASTER_DB_PASSWORD}
      - POSTGRES_DB=${MASTER_DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d etl_database -U mamun"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    logging:
      driver: none
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  server:
    container_name: go_server_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      postgres_db:
        condition: service_healthy
    links:
      - postgres_db:postgres_db
    volumes:
      - .:/app
    restart: always

volumes:
  postgres_data:
  pgadmin_data:
